// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

dotenv.config(); // Load .env first
dotenv.config({ path: path.resolve(".env.local"), override: true }); // Override with .env.local

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || process.env.PRISMA_DATABASE_URL,
  },
});
